### ISSUE TITLE
Unhandled Exception in Async Work

### ISSUE THREAD

**Issue by thw26** [ferion11/LogosLinuxInstaller#105]
This error is likely an upstream bug, but I am going to begin collecting data on this crash for submitting a WINE bug report.

Here is a full error output:

https://termbin.com/w3l7

I've triggered this primarily in two situations. First, when the Text Comparison Tool is open, I found that Logos regularly crashed when the Vulgate was an included translation. Second, when working in Aramaic on one of the Targums, slowly scrolling through the text I have noticed Logos will regularly crash.

I have noticed this in other situations, such as scrolling in the BHS apparatus or hovering over one of the links in the BHS apparatus causes it, but even other more mundane situations can cause this crash.

This is the main thing which blocks my Logos on Linux use from being pleasurable. If this were solved, I don't think I'd have any major issues.

**Comment by thw26** [comment]
This does appear to be related to mixing languages. When I have open Targum Psalms, Targum Lexicon, and HALOT, all synced together, the app crashes. If I remove HALOT, the app does not crash.

**Comment by thw26** [comment]
I thought this issue might pertain to resources of different languages being synced together when those resources are not, say, English and Hebrew/Greek.

As a test, I ran Targum Psalm (non-biblical Aramaic), the Targum Lexicon, and HALOT to see if this caused the issue; it did! But when I removed HALOT, the issue still happened with just the Targum Psalm and Targum Lexicon.

Given I found this issue happening with the apparatuses, the Vulgate, and these Aramaic resources, I'm wondering if it has more to deal with particular resources than something else.

**Comment by thw26** [comment]
I'm now also seeing this error in the library panel. I tried a two-word search "directory for" and the search ended while typing "for".

https://termbin.com/5my3

**Comment by thw26** [comment]
I thought it'd be worthwhile pulling one of the errors out of the async error's log entry:

```
System.AggregateException: One or more errors occurred. (Culture is not supported. (Parameter 'name')
eo is an invalid culture identifier.)
 ---> System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
eo is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureData.NlsEnumCultures(CultureTypes types)
   at System.Globalization.CultureData.GetCultures(CultureTypes types)
   at System.Globalization.CultureInfo.GetCultures(CultureTypes types)
   at Libronix.Utility.CultureInfoUtility.CreateSpecificCulture(LanguageName language)
   at Libronix.RichText.Conversions.RichTextToPlainText.Visitor.GetCultureInfoFromLanguage(LanguageName language)
   at Libronix.RichText.Conversions.RichTextToPlainText.Visitor.ProcessRunText(String strRunText)
   at Libronix.RichText.Conversions.RichTextToPlainText.Visitor.Visit(RichTextRun run)
   at Libronix.RichText.Conversions.RichTextToPlainText.Visitor.WriteSubtree()
   at Libronix.RichText.Conversions.RichTextToPlainText.Visitor.Visit(RichTextParagraph para)
   at Libronix.RichText.RichTextParagraph.Accept(IRichTextVisitor visitor)
   at Libronix.RichText.Conversions.RichTextToPlainText.Visitor.WriteSubtree()
   at Libronix.RichText.Conversions.RichTextToPlainText.Visitor.WriteToEnd()
   at Libronix.RichText.Conversions.RichTextToPlainText.Convert(IEnumerable`1 richText, TextWriter writerText, IWorkState state, RichTextToPlainTextSettings
 settings)
   at Libronix.RichText.Conversions.RichTextToPlainText.Convert(IEnumerable`1 richText, IWorkState state, RichTextToPlainTextSettings settings)
   at Libronix.RichText.Conversions.RichTextToPlainText.Convert(IEnumerable`1 richText, IWorkState state)
   at Libronix.DigitalLibrary.Resources.Logos.Controls.LogosDisplayElementAutomationPeer.GetTextRangeContent(ReadOnlyCollection`1 textRanges, IWorkState wor
kState)
   at Libronix.DigitalLibrary.Resources.Logos.Controls.LogosDisplayElementAutomationPeer.ComputeTextAsync(AsyncMethodContext context)
   --- End of inner exception stack trace ---wine: Call from 0000000170032138 to unimplemented function KERNEL32.dll.RaiseFailFastException, aborting
```

I wonder if this "CultureNotFoundException" is the source of the problem since it "is an invalid culture identifier".

**Comment by thw26** [comment]
I managed to fix this today after a reboot failed to fix it by removing the library catalog.

**Comment by thw26** [comment]
This time Logos failed and it failed with only the culture error:

https://pastebin.com/LqbCMpnU

**Comment by thw26** [comment]
cf. https://bugs.winehq.org/show_bug.cgi?id=52396#c8
